services:
  api_gateway_nest:
    build: ./http-api-gateway-nest
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway-nest/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
  hello_nest_microservice:
    build: ./hello-nest-microservice
    volumes:
      - ./hello-nest-microservice/src:/usr/src/app/src
    command: yarn start:dev
  nats:
    image: nats
    ports:
      - 4222:4222